name: "1. Quality Assurance"
description: "Automated CI for the demo-cicd-node project"

on:
  workflow_dispatch:
  push:
    branches: [develop, feature**, feat**. hotfix**, fix**]
  # pull_request:
  #   branches: [develop, main]

jobs:
  app:
    uses: heliomarpm/reusable-actions/.github/workflows/ci-quality-gate.yml@main
    # with:
    #   project_path: app
