name: "3. Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: heliomarpm/reusable-actions/.github/workflows/cd-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    # with:
    #   release_strategy: "release-branch"
    #   semantic_release_debug_mode: true
    #   semantic_release_dry_run: false
    #   strict_conventional_commits: false
